version: '3.1'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/service"
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/%2F
    networks:
      - nlp-network
    depends_on:
        - mongo
    command:
        python commands.py article-juejin -sit

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ${HOME}/datadir:/data/db
    networks:
      - nlp-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - nlp-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Song123654
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: qazwsx123
    depends_on:
      - mongo
    restart: always

    #  rabbit:
    #    image: rabbitmq:3-management
    #    container_name: rabbit
    #    ports:
    #        - "5672:5672"
    #        - "15672:15672"
    #    networks:
    #        - nlp-network

networks:
  nlp-network:
    driver: bridge
