version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ${HOME}/datadir:/data/db
    networks:
      - nlp-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - nlp-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Song123654
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: qazwsx123
    depends_on:
      - mongo

networks:
  nlp-network:
    driver: bridge
