version: '3.1'

services:

  juejin_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/service"
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/%2F
    networks:
      - nlp-network
    depends_on:
        - mongo
        - rabbit
    command:
        python main.py entrance --action segment --collection article-juejin

  cnblogs_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/service"
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/%2F
    networks:
      - nlp-network
    depends_on:
        - mongo
        - rabbit
    command:
        python main.py entrance --action segment --collection article-cnblogs

  csdn_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/service"
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/%2F
    networks:
      - nlp-network
    depends_on:
        - mongo
        - rabbit
    command:
        python main.py entrance --action segment --collection article-csdn

  tf_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/service"
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/%2F
    networks:
      - nlp-network
    depends_on:
        - mongo
        - rabbit
    command:
        python main.py bulk_calculate_tf -c article-juejin -c article-cnblogs -c article-csdn

  segment_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/service"
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/%2F
    networks:
      - nlp-network
    depends_on:
        - mongo
        - rabbit
    restart: always
    command:
        python main.py start_rabbit_workers --action segment

  tf_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/service"
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/%2F
    networks:
      - nlp-network
    depends_on:
        - mongo
        - rabbit
    restart: always
    command:
        python main.py start_rabbit_workers --action calculate_tf

  idf_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/service"
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/%2F
    networks:
      - nlp-network
    depends_on:
        - mongo
        - rabbit
    command:
        python main.py start_rabbit_workers --action calculate_idf

  tf_idf_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/service"
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/%2F
    networks:
      - nlp-network
    depends_on:
        - mongo
        - rabbit
    command:
        python main.py start_rabbit_workers --action calculate_tf_idf

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ${HOME}/datadir:/data/db
    networks:
      - nlp-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Song123654

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - nlp-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Song123654
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: qazwsx123
    depends_on:
      - mongo

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
        - nlp-network

networks:
  nlp-network:
    driver: bridge
